CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_id BIGINT NOT NULL UNIQUE,
    email VARCHAR(255),
    nickname VARCHAR(50) NOT NULL,
    profile_image_url VARCHAR(500),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);
COMMENT ON COLUMN users.role IS 'USER / ADMIN';

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    token_hash VARCHAR(300) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE seller_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    business_name VARCHAR(100) NOT NULL,
    business_number VARCHAR(20) NOT NULL,
    representative_name VARCHAR(50) NOT NULL,
    business_document_url VARCHAR(500),
    address VARCHAR(200),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    rejection_reason VARCHAR(500),
    applied_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by BIGINT REFERENCES users(id)
);
COMMENT ON COLUMN seller_application.status IS 'PENDING / APPROVED / REJECTED';

CREATE TABLE seller_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    seller_application_id BIGINT REFERENCES seller_application(id),
    business_name VARCHAR(100) NOT NULL,
    business_number VARCHAR(20) NOT NULL,
    representative_name VARCHAR(50) NOT NULL,
    address VARCHAR(200),
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    bank_name VARCHAR(50),
    account_number VARCHAR(100),
    account_holder VARCHAR(50),
    verification_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED',
    approved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);
COMMENT ON COLUMN seller_profile.verification_status IS 'APPROVED / SUSPENDED / REVOKED';

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_profile_id BIGINT NOT NULL REFERENCES seller_profile(id),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    category VARCHAR(30) NOT NULL,
    resource_type VARCHAR(20) NOT NULL,
    environment_type VARCHAR(20),
    total_quantity INTEGER NOT NULL,
    remaining_quantity INTEGER NOT NULL,
    original_price INTEGER NOT NULL,
    minimum_price INTEGER NOT NULL,
    current_price INTEGER NOT NULL,
    available_start_at TIMESTAMP WITH TIME ZONE,
    available_end_at TIMESTAMP WITH TIME ZONE,
    reservation_close_at TIMESTAMP WITH TIME ZONE NOT NULL,
    address VARCHAR(200),
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    foot_traffic_level VARCHAR(10),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);
COMMENT ON COLUMN product.category IS 'SAME_DAY_INVENTORY / EMPTY_TIME_RESOURCE / SAME_DAY_ROOM / TOUR_REMAINDER';
COMMENT ON COLUMN product.resource_type IS 'INVENTORY / SEAT / ROOM / EXPERIENCE / TOUR / RENTAL';
COMMENT ON COLUMN product.environment_type IS 'INDOOR / OUTDOOR';
COMMENT ON COLUMN product.foot_traffic_level IS 'LOW / MEDIUM / HIGH';
COMMENT ON COLUMN product.status IS 'DRAFT / ACTIVE / PAUSED / SOLD_OUT / CLOSED';

CREATE TABLE product_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id),
    image_url VARCHAR(500) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE price_recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id),
    recommended_price INTEGER NOT NULL,
    discount_rate DECIMAL(5,2),
    foot_traffic_level VARCHAR(10),
    weather_condition VARCHAR(50),
    tourist_flow_level VARCHAR(10),
    recommendation_reason VARCHAR(1000),
    strategy_message VARCHAR(1000),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE
);
COMMENT ON COLUMN price_recommendation.status IS 'PENDING / APPROVED / REJECTED / EXPIRED';

CREATE TABLE product_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id),
    price_recommendation_id BIGINT REFERENCES price_recommendation(id),
    previous_price INTEGER,
    changed_price INTEGER NOT NULL,
    change_type VARCHAR(30) NOT NULL,
    changed_by BIGINT REFERENCES users(id),
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON COLUMN product_price_history.change_type IS 'INITIAL / AI_RECOMMENDATION / SELLER_MANUAL / SYSTEM';

CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    quantity INTEGER NOT NULL,
    unit_price INTEGER NOT NULL,
    total_amount INTEGER NOT NULL,
    visit_start_at TIMESTAMP WITH TIME ZONE,
    visit_end_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    cancel_reason VARCHAR(500),
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP WITH TIME ZONE,
    rejected_at TIMESTAMP WITH TIME ZONE,
    canceled_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);
COMMENT ON COLUMN reservation.status IS 'REQUESTED / APPROVED / REJECTED / CANCELED / COMPLETED / NO_SHOW';

CREATE TABLE inventory_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id),
    reservation_id BIGINT REFERENCES reservation(id),
    changed_by BIGINT REFERENCES users(id),
    change_quantity INTEGER NOT NULL,
    quantity_after INTEGER NOT NULL,
    change_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON COLUMN inventory_history.change_type IS 'INITIAL / RESERVATION_APPROVED / RESERVATION_CANCELED / SELLER_ADJUSTMENT / SYSTEM_ADJUSTMENT';

CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservation(id),
    payment_key VARCHAR(200),
    order_id VARCHAR(100),
    amount INTEGER NOT NULL,
    payment_method VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    paid_at TIMESTAMP WITH TIME ZONE,
    canceled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);
COMMENT ON COLUMN payment.status IS 'PENDING / PAID / CANCELED / REFUNDED / FAILED';

CREATE TABLE wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    product_id BIGINT NOT NULL REFERENCES product(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wishlist_user_product UNIQUE (user_id, product_id)
);

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservation(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);
COMMENT ON COLUMN review.rating IS '1 ~ 5';

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    type VARCHAR(30) NOT NULL,
    title VARCHAR(100) NOT NULL,
    message VARCHAR(500),
    reference_type VARCHAR(30),
    reference_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE
);
COMMENT ON COLUMN notification.reference_type IS 'RESERVATION / PRODUCT / PAYMENT / SELLER_APPLICATION';

CREATE TABLE push_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    device_token VARCHAR(500) NOT NULL UNIQUE,
    platform VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);
COMMENT ON COLUMN push_token.platform IS 'FCM / APNS';

CREATE INDEX idx_refresh_token_user_id ON refresh_token(user_id);
CREATE INDEX idx_seller_application_user_id ON seller_application(user_id);
CREATE INDEX idx_seller_profile_user_id ON seller_profile(user_id);
CREATE INDEX idx_product_seller_profile_id ON product(seller_profile_id);
CREATE INDEX idx_product_status ON product(status);
CREATE INDEX idx_reservation_user_id ON reservation(user_id);
CREATE INDEX idx_reservation_product_id ON reservation(product_id);
CREATE INDEX idx_notification_user_id_is_read ON notification(user_id, is_read);
