ALTER TABLE refresh_token DROP CONSTRAINT refresh_token_user_id_fkey;
ALTER TABLE refresh_token ADD CONSTRAINT refresh_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE seller_application DROP CONSTRAINT seller_application_user_id_fkey;
ALTER TABLE seller_application ADD CONSTRAINT seller_application_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE seller_application DROP CONSTRAINT seller_application_reviewed_by_fkey;
ALTER TABLE seller_application ADD CONSTRAINT seller_application_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE seller_profile DROP CONSTRAINT seller_profile_user_id_fkey;
ALTER TABLE seller_profile ADD CONSTRAINT seller_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE seller_profile DROP CONSTRAINT seller_profile_seller_application_id_fkey;
ALTER TABLE seller_profile ADD CONSTRAINT seller_profile_seller_application_id_fkey FOREIGN KEY (seller_application_id) REFERENCES seller_application(id) ON DELETE CASCADE;
ALTER TABLE product DROP CONSTRAINT product_seller_profile_id_fkey;
ALTER TABLE product ADD CONSTRAINT product_seller_profile_id_fkey FOREIGN KEY (seller_profile_id) REFERENCES seller_profile(id) ON DELETE CASCADE;
ALTER TABLE product_image DROP CONSTRAINT product_image_product_id_fkey;
ALTER TABLE product_image ADD CONSTRAINT product_image_product_id_fkey FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
ALTER TABLE price_recommendation DROP CONSTRAINT price_recommendation_product_id_fkey;
ALTER TABLE price_recommendation ADD CONSTRAINT price_recommendation_product_id_fkey FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
ALTER TABLE product_price_history DROP CONSTRAINT product_price_history_product_id_fkey;
ALTER TABLE product_price_history ADD CONSTRAINT product_price_history_product_id_fkey FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
ALTER TABLE product_price_history DROP CONSTRAINT product_price_history_price_recommendation_id_fkey;
ALTER TABLE product_price_history ADD CONSTRAINT product_price_history_price_recommendation_id_fkey FOREIGN KEY (price_recommendation_id) REFERENCES price_recommendation(id) ON DELETE SET NULL;
ALTER TABLE product_price_history DROP CONSTRAINT product_price_history_changed_by_fkey;
ALTER TABLE product_price_history ADD CONSTRAINT product_price_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE reservation DROP CONSTRAINT reservation_product_id_fkey;
ALTER TABLE reservation ADD CONSTRAINT reservation_product_id_fkey FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
ALTER TABLE reservation DROP CONSTRAINT reservation_user_id_fkey;
ALTER TABLE reservation ADD CONSTRAINT reservation_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE inventory_history DROP CONSTRAINT inventory_history_product_id_fkey;
ALTER TABLE inventory_history ADD CONSTRAINT inventory_history_product_id_fkey FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
ALTER TABLE inventory_history DROP CONSTRAINT inventory_history_reservation_id_fkey;
ALTER TABLE inventory_history ADD CONSTRAINT inventory_history_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES reservation(id) ON DELETE CASCADE;
ALTER TABLE inventory_history DROP CONSTRAINT inventory_history_changed_by_fkey;
ALTER TABLE inventory_history ADD CONSTRAINT inventory_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE wishlist DROP CONSTRAINT wishlist_user_id_fkey;
ALTER TABLE wishlist ADD CONSTRAINT wishlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE wishlist DROP CONSTRAINT wishlist_product_id_fkey;
ALTER TABLE wishlist ADD CONSTRAINT wishlist_product_id_fkey FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
ALTER TABLE notification DROP CONSTRAINT notification_user_id_fkey;
ALTER TABLE notification ADD CONSTRAINT notification_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE push_token DROP CONSTRAINT push_token_user_id_fkey;
ALTER TABLE push_token ADD CONSTRAINT push_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
